services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    container_name: php
    working_dir: ${WORKING_DIR}
    user: ${HOST_UID}:${HOST_GID}
    volumes:
      - ${PROJECT_DIR}/:${WORKING_DIR}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
